### ISSUE TITLE
failed to compile in GAP 4.11.0

### ISSUE THREAD

**Issue by beew** [gap-packages/Semigroups#699]
After successfully compiling gap
run buid

```
CXX      src/semigroups_la-pkg.lo
src/pkg.cc: In function ‘Int InitKernel(StructInitInfo*)’:
src/pkg.cc:528:3: error: ‘CopyObjFuncs’ was not declared in this scope
CopyObjFuncs[T_SEMI]      = &TSemiObjCopyFunc;
^
src/pkg.cc:529:3: error: ‘CleanObjFuncs’ was not declared in this scope
CleanObjFuncs[T_SEMI]     = &TSemiObjCleanFunc;
^
Makefile:621: recipe for target 'src/semigroups_la-pkg.lo' failed
make[2]: Leaving directory '/home/bernard/opt/gap4/pkg/semigroups-3.2.3'
make[2]: *** [src/semigroups_la-pkg.lo] Error 1
Makefile:686: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/bernard/opt/gap4/pkg/semigroups-3.2.3'
make[1]: *** [all-recursive] Error 1
Makefile:463: recipe for target 'all' failed
make: *** [all] Error 2

WARNING: Failed to build semigroups-3.2.3
```
BuildPackages.sh

```

OS Ubuntu 16.04, gcc-5.4.0

**Comment by james-d-mitchell** [comment]
Can you please say which version of GAP you are using? I suspect that you are using the development version of GAP from github, and that contains some changes that break backwards compatibility in Semigroups. Perhaps @fingolfin or @ChrisJefferson can give a more detailed picture?

**Comment by beew** [comment]
Sorry, it is GAP 4.11.0

**Comment by james-d-mitchell** [comment]
I just downloaded GAP 4.11.0 and ran `BuildPackages.sh` and this compiled Semigroups 3.2.3 just fine. Not sure how to proceed. Could you maybe try: `./configure && make -j8` in the `semigroups-3.2.3` directory, and post the full log of what that produces? Thanks!

**Comment by beew** [comment]
@james-d-mitchell 

Hi, tried your suggestion and make errored out with

```
src/pkg.cc: In function ‘Int InitKernel(StructInitInfo*)’:
src/pkg.cc:528:3: error: ‘CopyObjFuncs’ was not declared in this scope
   CopyObjFuncs[T_SEMI]      = &TSemiObjCopyFunc;
   ^
src/pkg.cc:529:3: error: ‘CleanObjFuncs’ was not declared in this scope
   CleanObjFuncs[T_SEMI]     = &TSemiObjCleanFunc;
   ^
Makefile:621: recipe for target 'src/semigroups_la-pkg.lo' failed
make[2]: *** [src/semigroups_la-pkg.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/bernard/opt/gap4/pkg/semigroups-3.2.3'
Makefile:686: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/bernard/opt/gap4/pkg/semigroups-3.2.3'
Makefile:463: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by james-d-mitchell** [comment]
Thanks, this is curious. Could you please paste everything that you input and everything that comes out in the terminal from `./configure && make` to the errors above?
