### ISSUE TITLE
Semigroups fails to compile in gcc 5.3.1

### ISSUE THREAD

**Issue by mtorpey** [gap-packages/Semigroups#174]
In a recently-updated version of `gcc` (version 5.3.1) the Semigroups package fails to compile, giving the following output after `./autogen.sh`, `./configure`, and `make`:

```
[17:01:22] ~/gap/pkg/semigroups $ make
  CXX      src/semigroups_la-semigroups.lo
  CXX      src/semigroups_la-boolean.lo
  CXX      src/semigroups_la-types.lo
  CXX      src/semigroups_la-converter.lo
  CXX      src/semigroups_la-interface.lo
  CXX      src/semigroups_la-data.lo
  CXX      src/semigroups_la-bipart.lo
src/bipart.cc: In constructor ‘NrIdempotentsFinder::NrIdempotentsFinder(Bag, Bag, Bag, unsigned int, Bag)’:
src/bipart.cc:1149:23: error: ‘pow’ is not a member of ‘std’
         total_load += std::pow(_scc.back().size(), 2);
                       ^
src/bipart.cc:1149:23: note: suggested alternative:
In file included from /usr/include/features.h:361:0,
                 from /usr/include/stdlib.h:24,
                 from /home/mtorpey/gap/src/system.h:32,
                 from /home/mtorpey/gap/src/compiled.h:17,
                 from src/bipart.h:11,
                 from src/bipart.cc:10:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:153:1: note:   ‘pow’
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
 ^
Makefile:594: recipe for target 'src/semigroups_la-bipart.lo' failed
make: *** [src/semigroups_la-bipart.lo] Error 1
[17:01:38] ~/gap/pkg/semigroups $ gcc --version
gcc (Debian 5.3.1-17) 5.3.1 20160429
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[17:01:50] ~/gap/pkg/semigroups $ g++ --version
g++ (Debian 5.3.1-17) 5.3.1 20160429
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

For now we can get around this by using clang, or an older version of gcc (4.9 still works fine on my computer, and even 5.2 seems alright) - but we should support the latest gcc if possible.

**Comment by james-d-mitchell** [comment]
It appears that `std::pow(double, int)` was moved in C++11.  This is relatively easy to fix by just using `_scc.back().size() * _scc.back().size()` instead of `std::pow`. I'll do that later today.

**Comment by mtorpey** [comment]
This is fixed.
